# https://www.dartlang.org/guides/language/analysis-options
analyzer:
  strong-mode: true


linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - one_member_abstracts
    - slash_for_doc_comments
    - sort_constructors_first
