name: chronosgl
version: 1.1.0
author: rhulha <java4life@gmail.com>
description: A simple, minimal and elegant scene graph for WebGL written in Dart
homepage: https://github.com/rhulha/ChronosGL
dependencies:
  browser: any
  vector_math: '>=1.4.3 <=2.0.0'
