name: chronosgl
version: 3.3.0
authors:
- Robert Muth <robert@muth.org>
- Ray Hulha <java4life@gmail.com>
description: A simple WebGL2 engine written in Dart
homepage: https://github.com/ChronosTeam/ChronosGL
dependencies:
  vector_math: ">=2.0.5 <3.0.0"
  js: any
dev_dependencies:
  build_runner: ^0.8.8
  test: ">=0.12.20"
  args: ">=0.13.0"
  build_web_compilers: ^0.4.0
environment:
  sdk: ">=1.24.0 <= 2.0.0"
transformers:
- test/pub_serve:
    $include: test/**.dart
