name: chronosgl
version: 3.9.3
authors:
- Robert Muth <robert@muth.org>
- Ray Hulha <java4life@gmail.com>
description: A simple WebGL2 engine written in Dart
homepage: https://github.com/ChronosTeam/ChronosGL
dependencies:
  vector_math: ">=2.0.8 <3.0.0"
  js: ">= 0.6.1 <0.7.0"
dev_dependencies:
  build_runner: "any"
  build_daemon: ">=1.0.0 <2.0.0"
  build_test: "any"
  test: ">=1.5.3"
  args: ">=0.13.0"
  build_web_compilers: "any"
  io: ">=0.3.3"
  http: ">=0.11.3+17"
  vm_service_client: ">= 0.2.6"

environment:
  sdk: ">= 2.2.0 < 3.0.0"
