name: chronosgl
version: 3.2.3
authors:
- Robert Muth <robert@muth.org>
- Ray Hulha <java4life@gmail.com>
description: A simple WebGL2 engine written in Dart
homepage: https://github.com/ChronosTeam/ChronosGL
dependencies:
  vector_math: ">=2.0.5 <3.0.0"
dev_dependencies:
  browser: ">=0.10.0"
  test: ">=0.12.20"
  args: ">=0.13.0"
environment:
  sdk: ">=1.23.0 <2.0.0"
transformers:
- $dart2js:
    checked: true
    csp: true
    verbose: true
    commandLineOptions: ['--trust-type-annotations', '--trust-primitives',
 '--show-package-warnings', '--dump-info']
- test/pub_serve:
    $include: test/**.dart
